"""init

Revision ID: 66b74f6ba95e
Revises:
Create Date: 2025-05-22 15:46:28.989403

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "66b74f6ba95e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
