FROM python:3.12-slim

# set work directory
WORKDIR /opt

# set static environment variables
ENV PIP_NO_CACHE_DIR=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# copy pip file
COPY requirements.txt .

# install dependencies
RUN pip install -U pip setuptools wheel &&\
  pip install -r requirements.txt

# copy project
COPY migration/ migration/
COPY config/ config/

CMD ["alembic", "-c", "./config/alembic.ini", "upgrade", "head"]
